language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.9
  - DJANGO=1.9.2
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=1.4.22
    - python: "3.5"
      env: DJANGO_VERSION=1.5.12
    - python: "3.5"
      env: DJANGO_VERSION=1.6.11
    - python: "3.5"
      env: DJANGO_VERSION=1.7.11
    - python: "3.5"
      env: DJANGO_VERSION=1.8.9
install:
  - pip install coveralls gddkia-impediments-on-roads
  - pip install -q Django==$DJANGO
  - pip install --upgrade mock
script:
  - coverage run setup.py test
after_success:
  - coveralls