language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.9
  - DJANGO=1.9.2
install:
  - pip install coveralls gddkia-impediments-on-roads
  - pip install -q Django==$DJANGO
  - pip install --upgrade mock
script:
  - coverage run setup.py test
after_success:
  - coveralls